import logging

#
# Default settings

ENABLE_DATADOG_INTEGRATION = True
ENABLE_SENTRY_INTEGRATION = True

SENTRY_TRACES_SAMPLE_RATE = 0.0
BASE_URL = "localhost"
CODEBUILD_BUILD_NUMBER = "0.0"
SEND_FULL_REQUEST_TO_SENTRY = False
SENTRY_LOG_LEVEL = logging.ERROR
SENTRY_EVENT_LEVEL = logging.ERROR
SENTRY_INTEGRATIONS = []
